version: "3.7"

services:

  traefik:
    image: traefik:v1.7.18-alpine
    command:
      - "--configfile=/etc/traefik/traefik.toml"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    deploy:
      mode: global
      restart_policy:
        condition: any
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=8082"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.local,Path:/dashboard"
        - "traefik.docker.network=proxy_net"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true