version: '3.6'
services:
  api:
    image: ciscodevnet/rest-api-swagger:latest
    networks:
      - proxy_net
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`nginx.localhost`) && PathPrefix(`/hello`)"
        - "traefik.http.routers.api.service=api"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.services.api.loadbalancer.server.port=10010"
networks:
  proxy_net:
    external: true


#http://nginx.localhost/hello?name=Scott