version: '3.6'

services:
  traefik:
    image: "traefik:v2.4"
    hostname: "{{.Node.Hostname}}"
    command:
       - "--api.insecure=true"
       - "--providers.docker=true"
       - "--providers.docker.swarmmode=true"
       - "--providers.docker.exposedbydefault=false"
       - "--entrypoints.web.address=:80"
    ports:
       - target: 80
         published: 80
         protocol: tcp
         mode: host
       - target: 8080
         published: 8080
         protocol: tcp
         mode: host
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
       - proxy_net
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api_router.rule=Host(`traefik.localhost`) && ( PathPrefix(`/api`) || PathPrefix(`/dashboard`) )"
        - "traefik.http.routers.api_router.service=api@internal"
        - "traefik.http.routers.api_router.middlewares=api_auth"
        - "traefik.http.routers.api_router.entrypoints=web"
        - "traefik.http.services.api_service.loadbalancer.server.port=8080"
        # https://bcrypt-generator.com/ # $ = $$
        - "traefik.http.middlewares.api_auth.basicauth.users=admin:$$2y$$12$$iDQhqKA0q9DhjNxImC513eBrs1YY5V7xqslz45hKVB2plsk34pYNO "

networks:
  proxy_net:
    external: true