version: "3.3"

services:

  traefik:
    image: jarzamendia/traefik:grpc-web-lab
    command:
      - "--configfile=/etc/traefik/traefik.toml"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_net
    deploy:
      mode: global
      labels:
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.port=8082"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.local"
        - "traefik.docker.network=proxy_net"

  backend-envoy:
    image: jarzamendia/grpc-web-envoy:grpc-web-lab
    networks:
      - proxy_net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.port=8080"
        - "traefik.backend=backend-envoy"
        - "traefik.frontend.rule=Host:frontend.local"
        - "traefik.docker.network=proxy_net"

  node-server:  
    image: jarzamendia/grpc-web-server:grpc-web-lab
    networks:
      - proxy_net

  backend-client:
    image: jarzamendia/grpc-web-client:grpc-web-lab
    networks:
      - proxy_net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=8081"
        - "traefik.backend=backend-client"
        - "traefik.frontend.rule=Host:client.local"
        - "traefik.docker.network=proxy_net"

networks:
  proxy_net:
    external: true