# Arquivo de configuração inicial do Traefik.

debug = false
logLevel = "INFO"

#Log Files
[accessLog]
#    filePath = "/var/log/traefik/access.log"
     format = "json"
     bufferingSize = 100

[traefikLog]
#    filePath = "/var/log/traefik/traefik.log"
     format   = "json"

# Enable retry sending request if network error
# Default: (number servers in backend) -1
[retry]
attempts = 3

[respondingTimeouts]
# readTimeout is the maximum duration for reading the entire request, including the body.
# Default: "0s"
readTimeout = "0s"
# writeTimeout is the maximum duration before timing out writes of the response.
# Default: "0s"
writeTimeout = "0s"
# idleTimeout is the maximum duration an idle (keep-alive) connection will remain idle before closing itself.
# Default: "180s"
idleTimeout = "180s"

[forwardingTimeouts]
# dialTimeout is the amount of time to wait until a connection to a backend server can be established.
# Default: "30s"
dialTimeout = "30s"
# responseHeaderTimeout is the amount of time to wait for a server's response headers after fully writing the request (including its body, if any).
# Default: "0s"
responseHeaderTimeout = "0s"

InsecureSkipVerify = true

[ping]
  entryPoint = "http"

[api]
entryPoint = "traefik"
dashboard = true
debug = false

[api.statistics]
recentErrors = 10

[metrics]
    [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]

[docker]
watch = true
swarmmode = true
exposedByDefault = true

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.traefik]
  address = ":8082"